/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini client lazily to avoid crashing on startup if-key-is-missing
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      console.warn('GEMINI_API_KEY is missing. AI features will fallback to offline mock mode.');
    }
    aiClient = new GoogleGenAI({
      apiKey: key || 'dummy_key',
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

// API Routes
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', time: new Date().toISOString() });
});

// Heya AI Chat Copilot endpoint
app.post('/api/chat', async (req, res) => {
  const { messages, currentNodes, currentMuse } = req.body;

  try {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      // Mock mode fallback when no API key is provided
      const lastMsg = messages[messages.length - 1]?.content || '';
      let mockReply = `Hello! (Offline Mode) I can help you analyze your Field Map. I see you have ${currentNodes?.length || 0} nodes and ${currentMuse?.length || 0} muse items.`;
      let action: any = null;

      if (lastMsg.includes('node') || lastMsg.includes('节点') || lastMsg.includes('添加') || lastMsg.includes('create')) {
        mockReply += "\n\nI've created a new node for you on the map to help organize this task.";
        action = {
          type: 'create_node',
          data: {
            title: 'AI Draft Task',
            type: 'todo',
            description: 'This node was generated by Heya AI based on your discussion.',
            tags: ['AI', 'Draft'],
          }
        };
      } else {
        mockReply += "\n\nTry asking me to \"add a node\" or \"create an agent\" to see me manipulate the Field Map directly! Please configure your GEMINI_API_KEY in Settings to enable the smart LLM generator.";
      }

      return res.json({
        content: mockReply,
        action,
      });
    }

    const ai = getGeminiClient();

    // Construct a systemic context of the workspace
    const workspaceSnapshot = `
You are Heya AI, the intelligent workspace optimizer for "Heya/HeyaLab", a next-generation decentralized project field map and workspace.
The user is working on an infinite topological workspace composed of Project Nodes, Task Checklists, Muse ideas, and Agent Customizers. 

Current Workspace Snpashot:
- Active Map Nodes: ${JSON.stringify(currentNodes || [])}
- Muse Notes (Unstructured raw ideas): ${JSON.stringify(currentMuse || [])}

Your Goals:
1. Provide highly aesthetic, insightful, and practical design and implementation strategies for their P2P networks (Oermos), Agent decision structures (The Forge), and projects (Components).
2. You can manipulate the Field Map directly! If the user wants to add, connect, or update elements, you can output a special triggering action encoded as a JSON block in your markdown reply.

Triggering Actions format (always write this at the VERY END of your reply inside a markdown block block labeled with \`\`\`heya-action):
\`\`\`heya-action
{
  "type": "create_node",
  "data": {
    "title": "Node title",
    "type": "todo" | "project" | "agent" | "resource",
    "description": "Short description of what to do"
  }
}
\`\`\`
Or to recommend linking two nodes:
\`\`\`heya-action
{
  "type": "link_nodes",
  "data": {
    "sourceId": "id_of_source",
    "targetId": "id_of_target"
  }
}
\`\`\`
Or to add a structured idea to Muse:
\`\`\`heya-action
{
  "type": "create_muse",
  "data": {
    "content": "A brilliant unstructured spark..."
  }
}
\`\`\`

Explain your suggestions with a friendly, professional, Swiss-design-oriented tone. Highlight aesthetics, layout rhythm, 0ms latency engineering, and micro-flow customizers.
`;

    // Map conversation messages to GenAI SDK parts
    const contents = [
      { role: 'user', parts: [{ text: workspaceSnapshot }] },
      ...messages.map((m: any) => ({
        role: m.role === 'user' ? 'user' : 'model',
        parts: [{ text: m.content }],
      })),
    ];

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents,
    });

    const replyText = response.text || '';

    // Parse the reaction code block if present
    let action: any = null;
    const actionRegex = /```heya-action\s*([\s\S]*?)\s*```/i;
    const match = replyText.match(actionRegex);
    if (match && match[1]) {
      try {
        action = JSON.parse(match[1].trim());
      } catch (err) {
        console.error('Failed to parse heya-action JSON:', err);
      }
    }

    res.json({
      content: replyText,
      action,
    });
  } catch (error: any) {
    console.error('Error in Heya AI Chat service:', error);
    res.status(500).json({ error: error.message || 'AI service error' });
  }
});

// Setup Vite Dev Server / Static Assets
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    // Use vite middleware
    app.use(vite.middlewares);
  } else {
    // Production static serving
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`[Heya Server] Running on http://localhost:${PORT} in ${process.env.NODE_ENV || 'development'} mode`);
  });
}

startServer();
